//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public string PSComputerNAme { get; set; }
        public string SystemName { get; set; }
        public string Name { get; set; }
        public string Suffix { get; set; }
        public string Caption { get; set; }
        public string DisplayName { get; set; }
        public string PathName { get; set; }
        public string ServiceType { get; set; }
        public string StartMode { get; set; }
        public string Started { get; set; }
        public string State { get; set; }
        public string Status { get; set; }
        public long ExitCode { get; set; }
        public string Description { get; set; }
        public string DirName { get; set; }
        public string ProgramName { get; set; }
        public string Parameter { get; set; }
        public string ChangeState { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime CheckDate { get; set; }
        public int ComponentID { get; set; }
        public int ComputerID { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Computer Computer { get; set; }
    }
}
